import {
  Plane,
  ArchiveRestore,
  Archive,
  ArrowDownLeft,
  ArrowDownToLine,
  ArrowLeftRight,
  ArrowUpDown,
  ArrowUpRight,
  ArrowUpToLine,
  BadgeRussianRuble,
  Banknote,
  BookOpen,
  Briefcase,
  Bus,
  Calendar,
  Car,
  ChartPie,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  CircleDashed,
  CircleDollarSign,
  CircleEqual,
  CircleHelp,
  Clapperboard,
  ClipboardList,
  Clock,
  CloudAlert,
  Cloudy,
  CloudUpload,
  CreditCard,
  Delete,
  Dumbbell,
  Equal,
  Eye,
  EyeOff,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  Heart,
  Home,
  IdCard,
  Info,
  KeyRound,
  Laptop,
  Lightbulb,
  ListOrdered,
  LogOut,
  Menu,
  Pencil,
  PawPrint,
  Pill,
  Plus,
  RefreshCw,
  Repeat2,
  RotateCcw,
  Scissors,
  Search,
  Server,
  Settings,
  Shirt,
  ShoppingCart,
  Smartphone,
  Soup,
  Stethoscope,
  Tag,
  TrendingUp,
  Trash2,
  Type,
  Undo2,
  UserMinus,
  UserPlus,
  User,
  Users,
  Utensils,
  Wallet,
  Wifi,
  WifiOff,
  X,
  TriangleAlert,
  Inbox,
  LayoutGrid,
  AlignLeft,
  Baby,
  BedDouble,
  Bike,
  Bitcoin,
  Coins,
  Building2,
  BusFront,
  Cake,
  Camera,
  Carrot,
  Cat,
  Cloud,
  Coffee,
  Dog,
  Drama,
  Droplet,
  FileText,
  Flame,
  Glasses,
  Globe,
  HandHeart,
  Headphones,
  Key,
  Landmark,
  Leaf,
  Library,
  Luggage,
  Mail,
  Map,
  Megaphone,
  Monitor,
  Music,
  Paintbrush,
  PencilRuler,
  PlaneTakeoff,
  Percent,
  Phone,
  PlugZap,
  Repeat,
  Shield,
  Ship,
  ShoppingBag,
  ShoppingBasket,
  Sofa,
  Sparkles,
  SquareParking,
  Star,
  Store,
  Syringe,
  Tent,
  Ticket,
  TreePine,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  WashingMachine,
  Wine,
  Wrench,
  Zap,
  createLucideIcon
} from 'lucide-vue-next'
import type { Component } from 'vue'

// Not in the installed lucide version; paths copied from lucide `hamburger` (ISC).
const Hamburger = createLucideIcon('hamburger', [
  ['path', { d: 'M12 16H4a2 2 0 1 1 0-4h16a2 2 0 1 1 0 4h-4.25' }],
  ['path', { d: 'M5 12a2 2 0 0 1-2-2 9 7 0 0 1 18 0 2 2 0 0 1-2 2' }],
  ['path', { d: 'M5 16a2 2 0 0 0-2 2 3 3 0 0 0 3 3h12a3 3 0 0 0 3-3 2 2 0 0 0-2-2q0 0 0 0' }],
  ['path', { d: 'm6.67 12 6.13 4.6a2 2 0 0 0 2.8-.4l3.15-4.2' }]
])

const map: Record<string, Component> = {
  'cart.fill': ShoppingCart,
  'fork.knife': Utensils,
  'takeoutbag.and.cup.and.straw.fill': Soup,
  burger: Hamburger,
  'tram.fill': Bus,
  'car.fill': Car,
  'fuelpump.fill': Fuel,
  'house.fill': Home,
  'lightbulb.fill': Lightbulb,
  wifi: Wifi,
  iphone: Smartphone,
  'cross.case.fill': Stethoscope,
  'pills.fill': Pill,
  'dumbbell.fill': Dumbbell,
  'tshirt.fill': Shirt,
  'gift.fill': Gift,
  'pawprint.fill': PawPrint,
  'book.fill': BookOpen,
  'graduationcap.fill': GraduationCap,
  'gamecontroller.fill': Gamepad2,
  'film.fill': Clapperboard,
  airplane: Plane,
  'airplane.departure': PlaneTakeoff,
  scissors: Scissors,
  'hammer.fill': Hammer,
  'banknote.fill': Banknote,
  laptopcomputer: Laptop,
  'chart.line.uptrend.xyaxis': TrendingUp,
  'briefcase.fill': Briefcase,
  'creditcard.fill': CreditCard,
  'tag.fill': Tag,
  'heart.fill': Heart,
  'bag.fill': ShoppingBag,
  'basket.fill': ShoppingBasket,
  'storefront.fill': Store,
  'box.truck.fill': Truck,
  'cup.and.saucer.fill': Coffee,
  'wineglass.fill': Wine,
  'birthday.cake.fill': Cake,
  'carrot.fill': Carrot,
  'bus.fill': BusFront,
  bicycle: Bike,
  'parkingsign.circle.fill': SquareParking,
  'ferry.fill': Ship,
  'bolt.car.fill': PlugZap,
  'suitcase.fill': Luggage,
  'map.fill': Map,
  'tent.fill': Tent,
  'beach.umbrella.fill': Umbrella,
  'bed.double.fill': BedDouble,
  'sofa.fill': Sofa,
  'washer.fill': WashingMachine,
  'key.fill': Key,
  'building.2.fill': Building2,
  'drop.fill': Droplet,
  'flame.fill': Flame,
  'bolt.fill': Zap,
  'phone.fill': Phone,
  desktopcomputer: Monitor,
  'tv.fill': Tv,
  globe: Globe,
  'cloud.fill': Cloud,
  'arrow.triangle.2.circlepath': Repeat,
  'syringe.fill': Syringe,
  eyeglasses: Glasses,
  'teddybear.fill': Baby,
  'cat.fill': Cat,
  'dog.fill': Dog,
  'leaf.fill': Leaf,
  'tree.fill': TreePine,
  headphones: Headphones,
  'music.note': Music,
  'camera.fill': Camera,
  'paintbrush.fill': Paintbrush,
  'theatermasks.fill': Drama,
  'ticket.fill': Ticket,
  'trophy.fill': Trophy,
  'star.fill': Star,
  sparkles: Sparkles,
  'books.vertical.fill': Library,
  'pencil.and.ruler.fill': PencilRuler,
  'wrench.and.screwdriver.fill': Wrench,
  'building.columns.fill': Landmark,
  'doc.text.fill': FileText,
  'shield.fill': Shield,
  percent: Percent,
  'bitcoinsign.circle.fill': Bitcoin,
  'dollarsign.arrow.circlepath': Coins,
  'envelope.fill': Mail,
  'megaphone.fill': Megaphone,
  'hand.raised.fill': HandHeart,

  'arrow.up.arrow.down': ArrowUpDown,
  'arrow.up.arrow.down.circle': ArrowUpDown,
  'arrow.left.arrow.right': ArrowLeftRight,
  'arrow.left.arrow.right.circle.fill': Repeat2,
  'arrow.uturn.backward': Undo2,
  'arrow.uturn.backward.circle': RotateCcw,
  'arrow.uturn.backward.circle.fill': RotateCcw,
  'person.crop.circle.badge.minus': UserMinus,
  'person.crop.circle.badge.plus': UserPlus,
  'person.text.rectangle': IdCard,
  'person.2': Users,
  person: User,
  'person.badge.key': KeyRound,
  'circle.dashed': CircleDashed,

  calendar: Calendar,
  creditcard: CreditCard,
  banknote: Banknote,
  tag: Tag,
  textformat: Type,
  'text.alignleft': AlignLeft,
  'square.grid.2x2': LayoutGrid,
  'coloncurrencysign.circle': CircleDollarSign,
  'equal.circle': CircleEqual,
  equal: Equal,
  eye: Eye,
  'eye.slash': EyeOff,
  magnifyingglass: Search,
  'delete.backward': Delete,

  'icloud.and.arrow.up': CloudUpload,
  'exclamationmark.icloud': CloudAlert,
  'checkmark.icloud': Cloudy,
  'arrow.trianglehead.2.clockwise': RefreshCw,
  'clock.arrow.circlepath': Clock,
  'server.rack': Server,
  'checkmark.circle.fill': CheckCircle2,
  'wifi.slash': WifiOff,
  'square.and.arrow.down': ArrowDownToLine,
  'square.and.arrow.up': ArrowUpToLine,

  'list.bullet.rectangle.portrait': ClipboardList,
  'chart.pie': ChartPie,
  gearshape: Settings,
  plus: Plus,
  pencil: Pencil,
  trash: Trash2,
  checkmark: Check,
  xmark: X,
  'chevron.right': ChevronRight,
  'chevron.left': ChevronLeft,
  'chevron.down': ChevronDown,
  'chevron.up.chevron.down': ChevronsUpDown,
  archivebox: Archive,
  'tray.and.arrow.up': ArchiveRestore,
  tray: Inbox,
  'exclamationmark.triangle': TriangleAlert,
  'exclamationmark.triangle.fill': TriangleAlert,
  'info.circle.fill': Info,
  'questionmark.circle': CircleHelp,
  'rectangle.portrait.and.arrow.right': LogOut,
  'arrow.up.right': ArrowUpRight,
  'arrow.down.left': ArrowDownLeft,
  wallet: Wallet,
  list: ListOrdered,
  menu: Menu,
  ruble: BadgeRussianRuble
}

export const fallbackIcon: Component = Tag

export function iconFor(symbolName: string): Component {
  return map[symbolName] ?? fallbackIcon
}
