import {
  Plane,
  ArchiveRestore,
  Archive,
  ArrowDownLeft,
  ArrowDownToLine,
  ArrowLeftRight,
  ArrowUpDown,
  ArrowUpRight,
  ArrowUpToLine,
  BadgeRussianRuble,
  Banknote,
  BookOpen,
  Briefcase,
  Bus,
  Calendar,
  Car,
  ChartPie,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  CircleDashed,
  CircleDollarSign,
  CircleEqual,
  CircleHelp,
  Clapperboard,
  ClipboardList,
  Clock,
  CloudAlert,
  Cloudy,
  CloudUpload,
  CreditCard,
  Delete,
  Dumbbell,
  Equal,
  Eye,
  EyeOff,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  Heart,
  Home,
  IdCard,
  Info,
  KeyRound,
  Laptop,
  Lightbulb,
  ListOrdered,
  LogOut,
  Menu,
  Pencil,
  PawPrint,
  Pill,
  Plus,
  RefreshCw,
  Repeat2,
  RotateCcw,
  Scissors,
  Search,
  Server,
  Settings,
  Shirt,
  ShoppingCart,
  Smartphone,
  Soup,
  Stethoscope,
  Tag,
  TrendingUp,
  Trash2,
  Type,
  Undo2,
  UserMinus,
  UserPlus,
  User,
  Users,
  Utensils,
  Wallet,
  Wifi,
  WifiOff,
  X,
  TriangleAlert,
  Inbox,
  LayoutGrid,
  AlignLeft
} from 'lucide-vue-next'
import type { Component } from 'vue'

const map: Record<string, Component> = {
  'cart.fill': ShoppingCart,
  'fork.knife': Utensils,
  'takeoutbag.and.cup.and.straw.fill': Soup,
  'tram.fill': Bus,
  'car.fill': Car,
  'fuelpump.fill': Fuel,
  'house.fill': Home,
  'lightbulb.fill': Lightbulb,
  wifi: Wifi,
  iphone: Smartphone,
  'cross.case.fill': Stethoscope,
  'pills.fill': Pill,
  'dumbbell.fill': Dumbbell,
  'tshirt.fill': Shirt,
  'gift.fill': Gift,
  'pawprint.fill': PawPrint,
  'book.fill': BookOpen,
  'graduationcap.fill': GraduationCap,
  'gamecontroller.fill': Gamepad2,
  'film.fill': Clapperboard,
  airplane: Plane,
  scissors: Scissors,
  'hammer.fill': Hammer,
  'banknote.fill': Banknote,
  laptopcomputer: Laptop,
  'chart.line.uptrend.xyaxis': TrendingUp,
  'briefcase.fill': Briefcase,
  'creditcard.fill': CreditCard,
  'tag.fill': Tag,
  'heart.fill': Heart,

  'arrow.up.arrow.down': ArrowUpDown,
  'arrow.up.arrow.down.circle': ArrowUpDown,
  'arrow.left.arrow.right': ArrowLeftRight,
  'arrow.left.arrow.right.circle.fill': Repeat2,
  'arrow.uturn.backward': Undo2,
  'arrow.uturn.backward.circle': RotateCcw,
  'arrow.uturn.backward.circle.fill': RotateCcw,
  'person.crop.circle.badge.minus': UserMinus,
  'person.crop.circle.badge.plus': UserPlus,
  'person.text.rectangle': IdCard,
  'person.2': Users,
  person: User,
  'person.badge.key': KeyRound,
  'circle.dashed': CircleDashed,

  calendar: Calendar,
  creditcard: CreditCard,
  banknote: Banknote,
  tag: Tag,
  textformat: Type,
  'text.alignleft': AlignLeft,
  'square.grid.2x2': LayoutGrid,
  'coloncurrencysign.circle': CircleDollarSign,
  'equal.circle': CircleEqual,
  equal: Equal,
  eye: Eye,
  'eye.slash': EyeOff,
  magnifyingglass: Search,
  'delete.backward': Delete,

  'icloud.and.arrow.up': CloudUpload,
  'exclamationmark.icloud': CloudAlert,
  'checkmark.icloud': Cloudy,
  'arrow.trianglehead.2.clockwise': RefreshCw,
  'clock.arrow.circlepath': Clock,
  'server.rack': Server,
  'checkmark.circle.fill': CheckCircle2,
  'wifi.slash': WifiOff,
  'square.and.arrow.down': ArrowDownToLine,
  'square.and.arrow.up': ArrowUpToLine,

  'list.bullet.rectangle.portrait': ClipboardList,
  'chart.pie': ChartPie,
  gearshape: Settings,
  plus: Plus,
  pencil: Pencil,
  trash: Trash2,
  checkmark: Check,
  xmark: X,
  'chevron.right': ChevronRight,
  'chevron.left': ChevronLeft,
  'chevron.down': ChevronDown,
  'chevron.up.chevron.down': ChevronsUpDown,
  archivebox: Archive,
  'tray.and.arrow.up': ArchiveRestore,
  tray: Inbox,
  'exclamationmark.triangle': TriangleAlert,
  'exclamationmark.triangle.fill': TriangleAlert,
  'info.circle.fill': Info,
  'questionmark.circle': CircleHelp,
  'rectangle.portrait.and.arrow.right': LogOut,
  'arrow.up.right': ArrowUpRight,
  'arrow.down.left': ArrowDownLeft,
  wallet: Wallet,
  list: ListOrdered,
  menu: Menu,
  ruble: BadgeRussianRuble
}

export const fallbackIcon: Component = Tag

export function iconFor(symbolName: string): Component {
  return map[symbolName] ?? fallbackIcon
}
